# extract feature descriptors using pretrained model weights

expname: feature_extraction
# replace the following with your pretrained model path, img_dir and out_dir, respectively
ckpt_path: 'pretrained/last.pth'
extract_img_dir: '~/ImageDatasets/HPatches/'
extract_out_dir: '~/Descriptors/HPatches/odnet/'